[package]
name = "rusty_monitor"
version = "0.1.0"
edition = "2021"
authors = ["Joel Adjetey Komieter"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "3.3.0"
battery = "0.7.8"